dev_mode = 1  # set to 1 to see extended scoring break down and other notes
lb_mode  = 0  # future work: add "library builder" right into program as a third tab rather than have as separate script

# load custom written functions
source("source/Functions/asm-spec2dt.R")
source("source/Functions/asm-bpNormalizer.R")
source("source/Functions/asm-targetMolecules.R")
source("source/Functions/asm-spec2dt_ref.R")
source("source/Functions/asm-revMatchFactor.R")
source("source/Functions/asm-PeaksExplained.R")
source("source/Functions/asm-specImport.R")
source("source/Functions/asm-clc.R")
source("source/Functions/asm-mass-diff.R")
source("source/Functions/asm-hiRes2lowRes.R")

clc()

# Select Initial Library to view/search against
# future work: make this a selectable input in GUI? Or add all libraries from "Libraries folder" assuming each
# library has completely unique entries?
y = 1
Libraries = list.files("Libraries")
# if (y==1){
#   RefLibrary = readRDS("Libraries/NIST-DARTMS-Forensics-v1.RDS")
# } else if (y==2){
#   RefLibrary = readRDS("Libraries/RefLibForPaper.RDS")
# }

initial_RefLibrary = readRDS(paste0("Libraries/",Libraries[y]))
initial_RefLibSize = dim(initial_RefLibrary);

# need to make libraries reactive.

# Identify indices for each column in the library data table (for calling in app)
LibraryCats = colnames(initial_RefLibrary)
iCode = which(LibraryCats=="Code")
iName = which(LibraryCats=="Name")
iFormula = which(LibraryCats=="Formula")
iInChIKey = which(LibraryCats=="InChIKey_gen")
iPrecursorMZ = which(LibraryCats=="PrecursorMZ_gen")
iDimerProb = which(LibraryCats=="DimerProb")
iSmiles = which(LibraryCats=="SMILES")
iPotentialErrors = which(LibraryCats=="PotentialErrors")
iMassCaliError = which(LibraryCats=="MassCaliError")
iPotentialErrorsFM1 = which(LibraryCats=="PotentialErrorsFM1" )
iExactMass = which(LibraryCats=="AccurateMass_gen")
iStructure = which(LibraryCats=="Structure_gen")
iNoiseMetric = which(LibraryCats=="NoiseMetric")
iBP = which(LibraryCats=="BP")

iEnergies = which(LibraryCats=="Energies")
minEnFolder = initial_RefLibrary[1,iEnergies,with=FALSE][[1]][[1]][1]

if(dev_mode==1){
     DevModeMessage <- ({
          div(h2("DEVELOPMENT MODE"),br(),align="center")
     })
} else {
     DevModeMessage <- ({div("")})
}

DisclaimerMessage <- ({ 
         div(p("The NIST DART-MS Database Search Tool (DST)
         is an open-source research tool for analyzing DART-MS
         spectra of seized drugs. The authors cannot
         guarantee the accuracy nor validate the claims of
         others using results generated by this software."),
         style = "color:black;font-size:12pt")
})

EmailMessage <- ({
  div(HTML("<p>For help or more information: 
        <a href=\"mailto:dartdata@nist.gov\">
        dartdata@nist.gov
        </a></p>"),style="color:black;font-size:12pt")
})
